version: 2

models:
  - name: stg_marketing_events
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: event_year
        tests:
          - not_null
      - name: event_month
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      - name: event_timestamp
        tests:
          - not_null

  - name: stg_sales_transactions
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
      - name: transaction_year
        tests:
          - not_null
      - name: transaction_month
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      - name: user_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "revenue >= 0"
      - name: cost
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "cost >= 0"
      - name: transaction_timestamp
        tests:
          - not_null
  
  - name: stg_product_catalog
    columns:
      - name: product_id
        tests:
          - unique
          - not_null