version: 2

models:
  - name: stg_marketing_events
    description: "Staging model for marketing events data."
    columns:
      - name: event_id
        description: "Unique identifier for the marketing event."
        tests:
          - unique
          - not_null
      - name: event_year
        description: "Year of the marketing event."
        tests:
          - not_null
      - name: event_month
        description: "Month in number of the marketing event."
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      - name: user_id
        description: "Foreign key referencing the user."
      - name: event_type
        description: "Type of marketing event."
      - name: event_timestamp
        description: "Timestamp of the marketing event."
        tests:
          - not_null
      - name: channel
        description: "Marketing channel used for the event."
      - name: campaign
        description: "Marketing campaign associated with the event."
      - name: cost
        description: "Cost associated with the marketing event."

  - name: stg_sales_transactions
    description: "Staging model for sales transactions data."
    columns:
      - name: transaction_id
        description: "Unique identifier for the transaction."
        tests:
          - unique
          - not_null
      - name: transaction_year
        tests:
          - not_null
      - name: transaction_month
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      - name: user_id
        description: "Foreign key referencing the user."
        tests:
          - not_null
      - name: product_id
        description: "Foreign key referencing the product catalog."
        tests:
          - not_null
      - name: revenue
        description: "Revenue generated by the transaction."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "revenue >= 0"
      - name: cost
        description: "Cost associated with the transaction."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "cost >= 0"
      - name: transaction_timestamp
        description: "Timestamp of the transaction."
        tests:
          - not_null
  
  - name: stg_product_catalog
    description: "Staging model for product catalog data."
    columns:
      - name: product_id
        description: "Unique identifier for the product."
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Name of the product."
      - name: category
        description: "Category of the product."